// components/HomePageFooter.vue
<template>
  <footer id="footer">
    <p id="footer-text">
      Designed by
      <a target="_blank" href="https://github.com/Lycoon">Lycoon</a>
    </p>
  </footer>
</template>

<style scoped>
#footer {
  position: absolute;
  bottom: 1%;
  width: 100%;
}

#footer-text {
  font-size: 0.75vw;
}
</style>

// components/home/HomePageFooter.tsx
const HomePageFooter = () => {
    return (
        <footer id="footer">
            <p id="footer-text">
                <a
                    target="_blank"
                    rel="noreferrer"
                    href="https://github.com/Lycoon"
                >
                    About
                </a>{" "}
                | Contact
            </p>
        </footer>
    );
};

export default HomePageFooter;
