// components/EditorSidebar.vue
<template>
  <div id="sidebar" class="sidebar-shadow tabs">
    <EditorTab @click="setSceneHeading" content="SCENE HEADING" />
    <EditorTab @click="setAction" content="Action" />
    <EditorTab @click="setCharacter" content="CHARACTER" />
    <EditorTab @click="setDialogue" content="Dialogue" />
    <EditorTab @click="setParenthetical" content="(Parenthetical)" />
    <EditorTab @click="setTransition" content="TRANSITION:" />
    <EditorTab @click="setActStart" content="ACT START" />
    <EditorTab @click="setActEnd" content="ACT END" />
    <EditorTab @click="setNote" content="[[Note]]" />
  </div>
</template>

<script lang="ts">
export default {
  methods: {
    setSceneHeading() {
      console.log("setSceneHeading");
      //console.log(this.$store.state.editor);
    },

    setAction() {
      console.log("setAction");
    },

    setCharacter() {
      console.log("setCharacter");
    },

    setDialogue() {
      console.log("setDialogue");
    },

    setParenthetical() {
      console.log("setParenthetical");
    },

    setTransition() {
      console.log("setTransition");
    },

    setActStart() {
      console.log("setActStart");
    },

    setActEnd() {
      console.log("setActEnd");
    },

    setNote() {
      console.log("setNote");
    },
  },
};
</script>

<style scoped>
#sidebar {
  padding-top: 20px;
  background: #f0f0f0;
  min-width: max(10vw, 22vh);
}

.sidebar-shadow {
  box-shadow: -6px 0px 4px -2px rgba(0, 0, 0, 0.15);
}

.tabs {
  display: flex;
  flex-direction: column;
  justify-content: flex-start;
}
</style>

// components/EditorSidebar.tsx
import { useEditorState } from "../context/AppContext";
import EditorTab from "./EditorTab";

const EditorSidebar = () => {
  const { editor, updateEditor } = useEditorState();
  const updateNode = (node: string) => {
    console.log("Switched to node: " + node);
    editor?.chain().focus().toggleNode(node, node, {}).run();
  };
  const getSelectedNode = () => {};

  const setSceneHeading = () => {
    updateNode("SceneHeading");
  };

  const setAction = () => {
    updateNode("Action");
  };

  const setCharacter = () => {
    updateNode("Character");
  };

  const setDialogue = () => {
    updateNode("Dialogue");
  };

  const setParenthetical = () => {
    updateNode("Parenthetical");
  };

  const setTransition = () => {
    console.log(getSelectedNode());
    console.log(editor?.isActive("Dialogue"));
  };

  return (
    <div id="sidebar" className="sidebar-shadow tabs">
      <EditorTab action={setSceneHeading} content="SCENE HEADING" />
      <EditorTab action={setAction} content="Action" />
      <EditorTab action={setCharacter} content="CHARACTER" />
      <EditorTab action={setDialogue} content="Dialogue" />
      <EditorTab action={setParenthetical} content="(Parenthetical)" />
      <EditorTab action={setTransition} content="TRANSITION:" />
    </div>
  );
};

export default EditorSidebar;
