// src/components/HomePageNavbar.vue
<template>
  <nav class="navbar is-dark" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="http://localhost:8080">
        <img src="https://i.imgur.com/uIOrnUi.png" width="105" height="28" />
      </a>

      <a
        role="button"
        class="navbar-burger"
        aria-label="menu"
        aria-expanded="false"
        data-target="navbarBasicExample"
      >
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
            <a
              href="login"
              class="button is-light is-rounded is-small is-outlined"
              >Log in</a
            >
            <a
              href="register"
              class="button is-light is-rounded is-small is-outlined"
              >Create new account</a
            >
          </div>
        </div>
      </div>
    </div>
  </nav>
</template>

<script>
export default {};
</script>

<style></style>

// components/HomePageNavbar.tsx
import NavbarButton from "./NavbarButton";

const HomePageNavbar = (props: any) => {
  return (
    <nav id="navbar">
      <a id="logo" href="http://localhost:3000">
        <img src="https://i.imgur.com/uIOrnUi.png" width="100" height="28" />
      </a>
      <div id="navbar-buttons">
        <NavbarButton content="Log in" redirect="login"></NavbarButton>
        <NavbarButton
          content="Create account"
          redirect="register"
        ></NavbarButton>
      </div>
    </nav>
  );
};

export default HomePageNavbar;
