// pages/register.tsx
import type { NextPage } from "next";
import Head from "next/head";
import HomePageFooter from "../components/home/HomePageFooter";
import HomePageNavbar from "../components/navbar/Navbar";
import RegisterContainer from "../components/home/register/RegisterContainer";

const RegisterPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Scriptio - Register</title>
      </Head>
      <div className="main-container">
        <HomePageNavbar />
        <RegisterContainer />
        <HomePageFooter />
      </div>
    </>
  );
};

export default RegisterPage;

// src/views/Register.vue
<template>
  <div class="RegisterPage">
    <Navbar />
    <RegisterPage />
  </div>
</template>

<script>
import { Component, Vue } from "vue-property-decorator";
import RegisterPage from "@/components/RegisterPage.vue";
import Navbar from "@/components/HomePageNavbar.vue";

@Component({
  components: {
    RegisterPage,
    Navbar,
  },
})
export default class Register extends Vue {}
</script>
