// pages/editor.tsx
import type { NextPage } from "next";
import Head from "next/head";
import EditorContainer from "../components/editor/EditorContainer";
import HomePageNavbar from "../components/navbar/Navbar";

const EditorPage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Scriptio - Editor</title>
      </Head>
      <div className="main-container">
        <HomePageNavbar className="navbar" />
        <EditorContainer />
      </div>
    </div>
  );
};

export default EditorPage;

// pages/Editor.vue
<template>
  <div class="editor">
    <Navbar />
    <Editor />
    <HomePageFooter />
  </div>
</template>

<script lang="ts">
import Navbar from "@/components/HomePageNavbar.vue";
import Editor from "@/components/Editor.vue";

export default {
  components: {
    Navbar,
    Editor,
  },
  head: {
    title: "Scriptio - Editor",
  },
};
</script>
