// pages/login.tsx
import type { NextPage } from "next";
import Head from "next/head";
import HomePageFooter from "../components/home/HomePageFooter";
import HomePageNavbar from "../components/navbar/Navbar";
import LoginContainer from "../components/home/login/LoginContainer";

const LoginPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Scriptio - Log in</title>
      </Head>
      <div className="main-container">
        <HomePageNavbar />
        <LoginContainer />
        <HomePageFooter />
      </div>
    </>
  );
};

export default LoginPage;

// pages/Login.vue
<template>
  <div class="LoginPage">
    <Navbar />
    <div class="is-flex is-justify-content-center is-flex-direction-row">
      <LoginForm />
    </div>
    <HomePageFooter />
  </div>
</template>

<script lang="ts">
import Navbar from "@/components/HomePageNavbar.vue";

export default {
  components: {
    Navbar,
  },
  head: {
    title: "Scriptio - Log in",
  },
};
</script>
