// pages/Register.vue
<template>
  <div class="RegisterPage">
    <Navbar />
    <div class="is-flex is-justify-content-center is-flex-direction-row">
      <RegisterForm />
    </div>
    <HomePageFooter />
  </div>
</template>

<script lang="ts">
import Navbar from "@/components/HomePageNavbar.vue";

export default {
  components: {
    Navbar,
  },
  head: {
    title: "Scriptio - Register",
  },
};
</script>

// pages/register.tsx
import type { NextPage } from "next";
import Head from "next/head";
import HomePageFooter from "../components/home/HomePageFooter";
import HomePageNavbar from "../components/navbar/Navbar";
import RegisterContainer from "../components/home/register/RegisterContainer";

const RegisterPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Scriptio - Register</title>
      </Head>
      <div className="main-container">
        <HomePageNavbar />
        <RegisterContainer />
        <HomePageFooter />
      </div>
    </>
  );
};

export default RegisterPage;
